assistant_name: "lucy"
language: "en-US"

stt:                        # Speech-to-text
  engine: "speechrecognition"
  recognizer: "google"
  timeout_seconds: 6

tts:                        # Text-to-speech
  engine: "pyttsx3"
  voice: "Zira"

wake_words:
  - "lucy"
  - "hey lucy"

aliases:
  open: ["open", "launch", "start"]

sites:
  youtube: "https://www.youtube.com/"
  google: "https://www.google.com/"
  linkedin: "www.linkedin.com/in/deeptanshu-sharma-5814672b2"
  github: "https://github.com/DeeptanshuSharma1011"

apps:                       # NEW: Local apps Lucy can open
  notepad: "C:\\Windows\\notepad.exe"
  calculator: "C:\\Windows\\System32\\calc.exe"
  paint: "C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Accessories\\Paint.lnk"
  discord: "C:\\Users\\LENOVO\\AppData\\Local\\Discord\\Update.exe --processStart Discord.exe"
  mongodb: "C:\\Users\\LENOVO\\AppData\\Local\\MongoDBCompass\\MongoDBCompass.exe"
  brave: "C:\\Program Files\\BraveSoftware\\Brave-Browser\\Application\\brave.exe"
  capcut: "C:\\Users\\LENOVO\\AppData\\Local\\CapCut\\CapCut.exe --src3"
  whatsapp: "whatsapp.exe"
  word: "C:\\Program Files\\Microsoft Office\\root\\Office16\\WINWORD.EXE"
  powerpoint: "C:\\Program Files\\Microsoft Office\\root\\Office16\\POWERPNT.EXE"
  excel: "C:\\Program Files\\Microsoft Office\\root\\Office16\\EXCEL.EXE"
  microsoft edge: "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe"
  obs studio: "C:\\Program Files\\obs-studio\\bin\\64bit\\obs64.exe"
  control panel: "%windir%\\System32\\Control.exe"
  protonvpn: "C:\\Program Files\\Proton\\VPN\\ProtonVPN.Launcher.exe"

apis:                       # NEW: API keys for weather & news
  openweather:
    key: "88b914e36fbb17430ab5fc6ce4262d30"
    city: "New Delhi"
  newsapi:
    key: "c95ce95d98994842a10cda53f4e86220"
    country: "in"
